version: '2'
services:
  migrate:
    container_name: migrate
    image: alfredfrancis/ai-chatbot-framework:latest
    command: flask --app=manage  manage  migrate
    environment:
      APPLICATION_ENV: Production
    depends_on:
      - mongodb

  app:
    container_name: backend
    image: alfredfrancis/ai-chatbot-framework:latest
    hostname: backend
    environment:
      APPLICATION_ENV: Production
    ports:
      - 8080:80
    depends_on:
      - migrate
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:4.2.20
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data
volumes:
  mongodbdata:
